[package]
name = "src"
version = "0.1.0"
authors = ["lydia <lydi.dah@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
[[bin]]
name = "src"
path = "main.rs"
